import type { Metadata } from "next";
import { playfair, atkinsonMono, atkinsonNext } from "./fonts";
import '@/styles/globals.scss'



export const metadata: Metadata = {
  title: "My Lifestyle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playfair.variable} ${atkinsonMono.variable} ${atkinsonNext.variable}`}>
        {children}
      </body>
    </html>
  );
}
